# Generated by Django 3.2.13 on 2022-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=256)),
                ('group_location', models.CharField(max_length=256)),
                ('group_teacher', models.CharField(max_length=256)),
                ('group_manager', models.CharField(max_length=256)),
                ('group_region', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=256)),
                ('group_location', models.CharField(max_length=256)),
                ('group_teacher', models.CharField(max_length=256)),
                ('group_manager', models.CharField(max_length=256)),
                ('group_course', models.CharField(max_length=256)),
                ('report_date_start', models.CharField(max_length=256)),
                ('report_date_end', models.CharField(max_length=256)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('attended', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standart_name', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('lms_location_name', models.CharField(max_length=256)),
                ('region', models.CharField(choices=[('kyiv_city', 'kyiv_city'), ('kyiv_oblast', 'kyiv_oblast'), ('lviv_region', 'lviv_region'), ('chernivtsi_region', 'chernivtsi_region')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_manager', models.CharField(max_length=256)),
                ('client_name', models.CharField(max_length=256)),
                ('client_lms_id', models.CharField(max_length=256)),
                ('group_location', models.CharField(max_length=256)),
                ('group_course', models.CharField(max_length=256)),
                ('bussiness', models.CharField(max_length=256)),
                ('report_date_start', models.CharField(max_length=256)),
                ('report_date_end', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('total', models.IntegerField()),
                ('attended', models.IntegerField()),
                ('payments', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=256)),
                ('student_name', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('group_location', models.CharField(blank=True, max_length=256, null=True)),
                ('amo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
