# Generated by Django 3.2.13 on 2022-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='client_manager',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
