# Generated by Django 4.1.1 on 2023-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsConsolidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_location', models.CharField(max_length=256, null=True)),
                ('lms_location', models.CharField(max_length=256, null=True)),
                ('lms_group_id', models.CharField(max_length=16, null=True)),
                ('lms_student_id', models.CharField(max_length=16, null=True)),
                ('lms_student_name', models.CharField(max_length=256, null=True)),
                ('payment_student_name', models.CharField(max_length=256, null=True)),
                ('payment_total', models.IntegerField(null=True)),
                ('lms_total', models.IntegerField(null=True)),
                ('lms_group_label', models.CharField(max_length=256, null=True)),
                ('payment_group_label', models.CharField(max_length=256, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(default='todo', max_length=256, null=True)),
                ('comment', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
