# Generated by Django 4.1.1 on 2023-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lessonsconsolidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManagerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_manager', models.CharField(max_length=256, null=True)),
                ('territorial_manager', models.CharField(max_length=256, null=True)),
                ('regional_manager', models.CharField(max_length=256, null=True)),
                ('business', models.CharField(max_length=128, null=True)),
                ('total_attended', models.IntegerField()),
                ('total_payments', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('total_enrolled', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256, null=True)),
                ('regional_manager', models.CharField(max_length=256, null=True)),
                ('territorial_manager', models.CharField(max_length=256, null=True)),
                ('business', models.CharField(max_length=128, null=True)),
                ('total_attended', models.IntegerField()),
                ('total_payments', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('total_enrolled', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=256, null=True)),
                ('client_manager', models.CharField(max_length=256, null=True)),
                ('territorial_manager', models.CharField(max_length=256, null=True)),
                ('regional_manager', models.CharField(max_length=256, null=True)),
                ('business', models.CharField(max_length=128, null=True)),
                ('total_attended', models.IntegerField()),
                ('total_payments', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('total_enrolled', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
