# Generated by Django 3.2.13 on 2022-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='client_manager',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
