# Generated by Django 3.2.13 on 2022-07-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_location_client_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='group_location',
        ),
    ]
