# Generated by Django 4.1.1 on 2023-05-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clientmanagerreport_coursereport_locationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReportNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=256, null=True)),
                ('regional_manager', models.CharField(max_length=256, null=True)),
                ('territorial_manager', models.CharField(max_length=256, null=True)),
                ('business', models.CharField(max_length=128, null=True)),
                ('total_attended', models.IntegerField()),
                ('total_payments', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('total_enrolled', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
