# Generated by Django 3.2.13 on 2022-07-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location_territorial_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='students_without_payments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
