# Generated by Django 3.2.13 on 2022-07-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_report_students_without_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='students_without_payments',
            new_name='students_without_amo',
        ),
    ]
