# Generated by Django 3.2.13 on 2022-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_students_without_payments_report_students_without_amo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAMORef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
                ('amo_id', models.CharField(max_length=20)),
            ],
        ),
    ]
