# Generated by Django 3.2.13 on 2022-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_studentamoref'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentamoref',
            name='attended',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentamoref',
            name='group_id',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
