# Generated by Django 3.2.13 on 2022-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220731_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='territorial_manager',
            field=models.CharField(default=True, max_length=256),
        ),
    ]
