# Generated by Django 3.2.13 on 2022-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_report_territorial_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='territorial_manager',
            field=models.CharField(default='', max_length=256),
        ),
    ]
