# Generated by Django 3.2.13 on 2022-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_report_territorial_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentamoref',
            name='report_end',
            field=models.CharField(default='2022-02-06', max_length=64),
        ),
        migrations.AddField(
            model_name='studentamoref',
            name='report_start',
            field=models.CharField(default='2022-02-01', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('UA_Kievskaya oblast', 'UA_Kievskaya oblast'), ('UA_Kiev', 'UA_Kiev'), ('UA_Odessa', 'UA_Odessa'), ('UA_Kharkov', 'UA_Kharkov'), ('UA_Dnepr', 'UA_Dnepr'), ('UA_SaaS', 'UA_SaaS'), ('UA_Odesskaya oblast', 'UA_Odesskaya oblast'), ('UA_Vynnytsya', 'UA_Vynnytsya'), ('UA_Dnepropetrovskaya oblast', 'UA_Dnepropetrovskaya oblast'), ('UA_Chernivtsi', 'UA_Chernivtsi'), ('UA_Lviv', 'UA_Lviv'), ('UA_ChernivtsiOblast', 'UA_ChernivtsiOblast'), ('UA_LvivOblast', 'UA_LvivOblast'), ('UA_VynnytsyaOblast', 'UA_VynnytsyaOblast'), ('UA_Dnepr_region', 'UA_Dnepr_region'), ('UA_Poltava', 'UA_Poltava'), ('UA_Chernigov_obl', 'UA_Chernigov_obl'), ('UA_Donetskobl', 'UA_Donetskobl'), ('UA_Center', 'UA_Center'), ('UA_Nikolaevskaya_obl', 'UA_Nikolaevskaya_obl'), ('UA_Dnepropetrovskaya oblast2', 'UA_Dnepropetrovskaya oblast2')], default=None, max_length=200, null=True),
        ),
    ]
