# Generated by Django 3.2.13 on 2022-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220819_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='business',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
