# Generated by Django 3.2.13 on 2022-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_report_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='regional_manager',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
