# Generated by Django 3.2.13 on 2022-08-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_report_client_manager'),
    ]

    operations = [
    ]
