# Generated by Django 3.2.13 on 2022-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220828_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=256)),
                ('report_start', models.CharField(max_length=256)),
                ('report_end', models.CharField(max_length=256)),
                ('issue_description', models.CharField(max_length=2048)),
                ('issue_status', models.CharField(max_length=128)),
                ('issue_priority', models.CharField(max_length=128)),
                ('issue_roles', models.CharField(max_length=1024)),
            ],
        ),
    ]
