# Generated by Django 3.2.13 on 2022-08-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_data',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_header',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
