# Generated by Django 3.2.13 on 2022-08-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_issue_issue_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_data',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_header',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
    ]
