# Generated by Django 3.2.13 on 2022-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220828_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tutor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
