# Generated by Django 3.2.13 on 2022-09-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220901_0600'),
    ]

    operations = [
    ]
