# Generated by Django 4.1.1 on 2022-09-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220901_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalGroup',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
