# Generated by Django 4.1.1 on 2022-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_delete_globalgroup_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher", models.CharField(blank=True, max_length=256, null=True)),
                ("attended", models.IntegerField()),
                ("payments", models.IntegerField()),
                ("conversion", models.FloatField()),
                ("location_name", models.CharField(max_length=256)),
                ("region", models.CharField(max_length=256)),
                ("territorial_manager", models.CharField(default="", max_length=256)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("business", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "regional_manager",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("tutor", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
