# Generated by Django 4.1.1 on 2022-09-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_teacherreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lms_id", models.CharField(max_length=16)),
                ("group_name", models.CharField(max_length=256)),
                ("teacher", models.CharField(max_length=256)),
                ("client_manager", models.CharField(max_length=256)),
                ("group_type", models.CharField(max_length=256)),
                ("status", models.CharField(max_length=256)),
                ("region", models.CharField(max_length=256)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="home.location",
                    ),
                ),
            ],
        ),
    ]
