# Generated by Django 4.1.1 on 2022-09-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_globalgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalgroup",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.location",
            ),
        ),
    ]
