# Generated by Django 4.1.1 on 2022-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_globalgroup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalgroup",
            name="course",
            field=models.CharField(default="not_assigned", max_length=512),
            preserve_default=False,
        ),
    ]
