# Generated by Django 4.1.1 on 2022-09-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_globalgroup_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_lms_id", models.CharField(max_length=16)),
                ("student_first_name", models.CharField(max_length=128)),
                ("student_last_name", models.CharField(max_length=128)),
                ("enrolled_md", models.IntegerField()),
                ("attended_mc", models.IntegerField()),
                ("payment", models.IntegerField()),
                ("teacher", models.CharField(max_length=256)),
                ("client_manager", models.CharField(max_length=256)),
                ("territorial_manager", models.CharField(max_length=256)),
                ("regional_manager", models.CharField(max_length=256)),
                ("tutor", models.CharField(max_length=256)),
                (
                    "business",
                    models.CharField(
                        choices=[
                            ("programming", "programming"),
                            ("english", "english"),
                        ],
                        max_length=200,
                    ),
                ),
                ("course", models.CharField(max_length=1024)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "student_current_group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_current",
                        to="home.globalgroup",
                    ),
                ),
                (
                    "student_mk_group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_mk",
                        to="home.globalgroup",
                    ),
                ),
            ],
        ),
    ]
