# Generated by Django 4.1.1 on 2022-09-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_studentreport_is_duplicate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentreport",
            old_name="enrolled_md",
            new_name="enrolled_mc",
        ),
    ]
