# Generated by Django 4.1.1 on 2022-09-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_studentreport_amo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreport",
            name="location",
            field=models.CharField(default=None, max_length=256),
        ),
    ]
