# Generated by Django 4.1.1 on 2022-09-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_alter_studentreport_student_current_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentreport",
            name="amo_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="client_manager",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="course",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="location",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="regional_manager",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="student_mk_group_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_mk",
                to="home.globalgroup",
            ),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="teacher",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="territorial_manager",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="tutor",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
