# Generated by Django 4.1.1 on 2022-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_alter_studentreport_amo_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalgroup",
            name="full_course",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
