# Generated by Django 4.1.1 on 2022-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_location_tutor_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="client_manager_english",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
