# Generated by Django 4.1.1 on 2022-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_location_client_manager_english"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentreport",
            name="attended_mc",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="business",
            field=models.CharField(
                choices=[("programming", "programming"), ("english", "english")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="enrolled_mc",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="payment",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="student_first_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="student_last_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="student_lms_id",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
