# Generated by Django 4.1.1 on 2022-11-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_issue_issue_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="issue_step",
        ),
    ]
