# Generated by Django 4.1.1 on 2022-12-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0042_remove_issue_issue_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('auth_token', models.CharField(max_length=256, null=True)),
                ('login_timestamp', models.DateTimeField(null=True)),
                ('related_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
