# Generated by Django 4.2 on 2023-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_alter_course_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("english", "Англійська"),
                    ("programming", "Програмування"),
                    ("unknown", "Невідомо"),
                ],
                max_length=256,
            ),
        ),
    ]
