# Generated by Django 4.2 on 2023-05-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("lesson_datetime", models.DateTimeField()),
                ("lesson_course", models.CharField(max_length=256)),
                ("lesson_type", models.CharField(max_length=256)),
                ("lesson_status", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("is_english", models.BooleanField(default=False)),
                ("is_programming", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_lms_id", models.CharField(max_length=100)),
                ("group_title", models.CharField(max_length=256)),
                ("group_course", models.CharField(max_length=256)),
                ("group_lesson_count", models.IntegerField(default=36)),
                ("start_date", models.DateField()),
                (
                    "group_lessons",
                    models.ManyToManyField(blank=True, to="teachers.lesson"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
