# Generated by Django 4.2 on 2023-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachergroup",
            name="group_location",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
