# Generated by Django 4.2 on 2023-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_teachergroup_group_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("lms_course_id", models.CharField(max_length=100)),
                ("course_type", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
