# Generated by Django 4.2 on 2023-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0006_course_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="tutor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
