# Generated by Django 4.2 on 2023-06-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0008_teacher_location_lessonslibrary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("lesson_course", models.CharField(max_length=256)),
                ("lesson_type", models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name="LessonsLibrary",
        ),
        migrations.AddField(
            model_name="course",
            name="course_lessons",
            field=models.ManyToManyField(blank=True, to="teachers.courselesson"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="related_course_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.courselesson",
            ),
        ),
    ]
