# Generated by Django 4.2 on 2023-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0009_courselesson_delete_lessonslibrary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("english", "Англійська"),
                    ("programming", "Програмування"),
                    ("unknown", "Невідомо"),
                    ("other", "Інше"),
                ],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("regular", "Звичайний урок"),
                    ("open_lesson", "Відкритий урок"),
                    ("parents_meeting", "Збори з батьками"),
                ],
                max_length=256,
            ),
        ),
    ]
