# Generated by Django 4.2 on 2023-06-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0012_lesson_lesson_number_alter_lesson_lesson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachergroup",
            name="start_date",
            field=models.DateField(blank=True),
        ),
    ]
