# Generated by Django 4.2 on 2023-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0013_alter_teachergroup_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachergroup",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
