# Generated by Django 4.2 on 2023-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0014_alter_teachergroup_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="location",
        ),
    ]
