# Generated by Django 4.2 on 2023-06-09 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0015_remove_teacher_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="tutor",
        ),
        migrations.AddField(
            model_name="teacher",
            name="tutors",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
