# Generated by Django 4.2 on 2023-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0016_remove_teacher_tutor_teacher_tutors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
