# Generated by Django 4.2 on 2023-06-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0017_alter_lesson_lesson_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="score",
            field=models.CharField(
                blank=True, default="0.00", max_length=256, null=True
            ),
        ),
    ]
